config/routes.rb
Westendathletic::Application.routes.draw do

	root :to => 'home#index'

  namespace :admin do

  	root :to => 'dashboard#index'

	  resource :session,
    	:only => [:new, :create, :destroy]

    resources :users,
      :except => [:show]

    resources :teams, :competitions

    resources :players, :seasons,
      :except => [:index]

    get 'seasons/:id/teams' => 'seasons#teams', :as => :season_teams
    put 'seasons/:id/teams' => 'seasons#update_teams', :as => :season_teams

	end

end

app/models/season.rb
class Season < ActiveRecord::Base

  attr_accessible :name, :start_date, :end_date, :competition_id

  validates :name, :start_date, :competition,
  	:presence => true

  validates :name,
  	:length => { :maximum => 255 }

  belongs_to :competition
  has_and_belongs_to_many :teams

end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < ApplicationController

  before_filter :authorisation_required

  # GET /admin/seasons/1
  def show
    @season = Season.find(params[:id])
  end

  # GET /admin/seasons/new
  def new
    @season = Competition.find(params[:competition_id]).seasons.new
  end

  # GET /admin/seasons/1/edit
  def edit
    @season = Season.find(params[:id])
  end

  # POST /admin/seasons
  def create
    @season = Season.new(params[:season])

    if @season.save
      flash[:success] = 'Season was successfully created.'
      redirect_to admin_competition_path(@season.competition)
    else
      flash.now[:error] = 'Season creation was unsuccessful.'
      render :new
    end
  end

  # PUT /admin/seasons/1
  def update
    @season = Season.find(params[:id])

    if @season.update_attributes(params[:season])
      flash[:success] = 'Season was successfully updated.'
      redirect_to admin_competition_path(@season.competition)
    else
      flash.now[:error] = 'Season edit was unsuccessful.'
      render :edit
    end
  end

  # DELETE /admin/seasons/1
  def destroy
    @season = Season.find(params[:id])
    competition = @season.competition
    @season.destroy

    flash[:notice] = 'Season was successfully destroyed.'
    redirect_to admin_competition_path(competition)
  end

  # GET /admin/seasons/1/teams
  def teams
    @season = Season.find(params[:id])
  end

  # PUT /admin/seasons/1/teams
  def update_teams
    @season = Season.find(params[:id])
    @season.teams = Team.find_all_by_id(params[:teams].values.to_a)

    if @season.save
      flash[:success] = 'Teams successfully updated for this season.'
      redirect_to admin_season_path(@season)
    else
      flash.now[:error] = 'Teams edit for this season was unsuccessful.'
      render :teams
    end
  end

end

app/helpers/seasons_helper.rb
module SeasonsHelper

	def get_teams_hash
		Hash.new.tap do |teams_hash|
			Team.all.each do |team|
				teams_hash[team.name] = team.id
			end
		end
	end

end

app/views/admin/seasons/_form.html.erb
<%= form_for([:admin, @season], :html => {:class => 'form-horizontal well'}) do |f| %>

  <%= f.hidden_field :competition_id %>

  <fieldset>

    <div class="control-group <%= 'error' if @season.errors[:name].any? %>">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
        <span class="help-inline"><%= @season.errors[:name].join(", ") %></span>
      </div>
    </div>

    <div class="control-group <%= 'error' if @season.errors[:start_date].any? %>">
      <%= f.label :start_date, :class => 'control-label' %>
      <div class="controls date-resize">
        <%= 
          f.date_select :start_date, 
          {
            :order => [:day, :month, :year],
            :prompt => { :day => 'Day', :month => 'Month', :year => 'Year' }
          } 
        %>
        <span class="help-inline"><%= @season.errors[:start_date].join(", ") %></span>
      </div>
    </div>

    <div class="control-group <%= 'error' if @season.errors[:end_date].any? %>">
      <%= f.label :end_date, :class => 'control-label' %>
      <div class="controls date-resize">
       <%= 
          f.date_select :end_date, 
          {
            :order => [:day, :month, :year],
            :prompt => { :day => 'Day', :month => 'Month', :year => 'Year' }
          } 
        %>
        <span class="help-inline"><%= @season.errors[:end_date].join(", ") %></span>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_competition_path(@season.competition), :class => 'btn' %>
    </div>

</fieldset>

<% end %>

app/views/admin/seasons/_header.html.erb
<div class="page-header">
  <h1>Competition Management</h1>
</div>

app/views/admin/seasons/_teams_form.html.erb
<%= form_for([:admin, @season], :url => admin_season_teams_path, :html => {:id => 'js_teams', :class => 'form-horizontal well'}) do |f| %>

  <fieldset>

    <% @season.teams.each_with_index do |team, index| %>
    <div class="control-group">
      <div class="controls">
        <%= select_tag "teams[#{index}]", options_for_select(get_teams_hash, team.id), :prompt => 'Select Team' %>
        <span class="help-inline">
          <%= link_to 'Remove', '#', { :class => 'js_remove_team btn btn-danger btn-mini' } %>
        </span>
      </div>
    </div>
    <% end %>

    <% if @season.teams.empty? %>
    <div class="control-group">
      <div class="controls">
        <%= select_tag "teams[0]", options_for_select(get_teams_hash), :prompt => 'Select Team' %>
        <span class="help-inline">
          <%= link_to 'Remove', '#', { :class => 'js_remove_team btn btn-danger btn-mini' } %>
        </span>
      </div>
    </div>
    <% end%>

    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_season_path(@season), :class => 'btn' %>
    </div>

  </fieldset>

<% end %>

app/views/admin/seasons/edit.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">
  	<div class="bordered">
  		<h2>Edit Season</h2>
    	<%= render 'form' %>
    </div>
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/seasons/new.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">
  	<div class="bordered">
  		<h2>New Season</h2>
    	<%= render 'form' %>
    </div>
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/seasons/show.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">

  	<div class="bordered">

  		<div class="pull-right">
        <%= link_to 'Back', admin_competition_path(@season.competition), :class => 'btn' %>
        <%= link_to 'Edit Teams', admin_season_teams_path(@season), :class => 'btn btn-primary' %>
      </div>

  		<h2><%= @season.name %></h2>
      <p><strong>Start Date: </strong> <%= @season.start_date %></p>
      <p><strong>End Date: </strong> <%= @season.end_date %></p>

      <table class="table table-striped table-bordered">

        <thead>
          <tr>
            <th>Pos</th>
            <th>Name</th>
            <th>P</th>
            <th>W</th>
            <th>D</th>
            <th>L</th>
            <th>F</th>
            <th>A</th>
            <th>GD</th>
            <th>R</th>
            <th>Y</th>
            <th>Pts</th>
          </tr>
        </thead>

        <tbody>

          <% @season.teams.each do |team| %>
          <tr>
            <td>0</td>
            <td><%= link_to team.name, admin_team_path(team) %></td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
          </tr>
          <% end %>

          <% if @season.teams.empty? %>
          <tr>
            <td colspan="12">There are no teams.</td>
          </tr>
          <% end %>

        </tbody>

      </table>

    </div>

  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/seasons/teams.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">
  	<div class="bordered">

      <div class="pull-right">
        <%= link_to 'Add Team', '#', { :id => 'js_add_team', :class => 'btn' } %>
      </div>

  		<h2>Edit Season Teams</h2>

    	<%= render 'teams_form' %>

    </div>
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

<script type="text/javascript">

	$(document).ready(function() {

    westendathletic.seasons.teams.init({
      addTeamButtonId: '#js_add_team',
      removeTeamButtonClass: '.js_remove_team',
      teamControlGroupClass: '.control-group'
    });

  });

</script>