config/routes.rb
Westendathletic::Application.routes.draw do

	root :to => 'home#index'

  namespace :admin do

  	root :to => 'dashboard#index'

	  resource :session,
    	:only => [:new, :create, :destroy]

    resources :users,
      :except => [:show]

    resources :teams, :competitions

    resources :players, :seasons,
      :except => [:index]

    get 'seasons/:id/teams' => 'seasons#teams', :as => :season_teams
    put 'seasons/:id/teams' => 'seasons#update_teams', :as => :season_teams

	end

end

app/models/team.rb
class Team < ActiveRecord::Base

  attr_accessible :name, :info, :home_team

  validates :name,
  	:presence => true, :length => { :maximum => 255 }

  validates :info,
  	:length => { :maximum => 1020 }

  has_many :players
  has_and_belongs_to_many :seasons

end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController

	before_filter :authorisation_required

  # GET /admin/teams
  def index
    @teams = Team.all
  end

  # GET /admin/teams/1
  def show
    @team = Team.find(params[:id])
  end

  # GET /admin/teams/new
  def new
    @team = Team.new
  end

  # GET /admin/teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /admin/teams
  def create
    @team = Team.new(params[:team])

    if @team.save
      flash[:success] = 'Team was successfully created.'
      redirect_to admin_teams_path
    else
      flash.now[:error] = 'Team creation was unsuccessful.'
      render :new
    end
  end

  # PUT /admin/teams/1
  def update
    @team = Team.find(params[:id])

    if @team.update_attributes(params[:team])
      flash[:success] = 'Team was successfully updated.'
      redirect_to admin_teams_path
    else
      flash.now[:error] = 'Team edit was unsuccessful.'
      render :edit
    end
  end

  # DELETE /admin/teams/1
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    flash[:notice] = 'Team was successfully destroyed.'
    redirect_to admin_teams_path
  end

end

app/views/admin/teams/_form.html.erb
<%= form_for([:admin, @team], :html => {:class => 'form-horizontal well'}) do |f| %>

  <fieldset>

    <div class="control-group <%= 'error' if @team.errors[:name].any? %>">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
        <span class="help-inline"><%= @team.errors[:name].join(", ") %></span>
      </div>
    </div>

    <div class="control-group <%= 'error' if @team.errors[:info].any? %>">
      <%= f.label :info, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :info, :rows => 5, :cols => 0 %>
        <span class="help-inline"><%= @team.errors[:info].join(", ") %></span>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_teams_path, :class => 'btn' %>
    </div>

</fieldset>

<% end %>

app/views/admin/teams/_header.html.erb
<div class="page-header">
  <h1>Team Management</h1>
</div>

app/views/admin/teams/edit.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">
  	<div class="bordered">
  		<h2>Edit Team</h2>
    	<%= render 'form' %>
    </div>
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/teams/index.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">

    <div class="bordered">

      <h2>Teams</h2>

      <table class="table table-striped table-bordered">

        <thead>
          <tr>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>

          <% @teams.each do |team| %>
          <tr>
            <td><%= link_to team.name, admin_team_players_path(team) %></td>
            <td>
              <%= link_to 'Edit Team', edit_admin_team_path(team), :class => 'btn' %>
              <%= 
                link_to 'Delete Team', '#deleteItem', 
                'data-url' => admin_team_path(team),
                'data-name' => team.name, 
                :class => 'btn btn-danger delete' 
              %>
            </td>
          </tr>
          <% end %>

        </tbody>

      </table>

      <%= link_to 'New Team', new_admin_team_path, :class => 'btn btn-primary' %>

    </div>
    
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/teams/new.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">
  	<div class="bordered">
  		<h2>New Team</h2>
    	<%= render 'form' %>
    </div>
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/teams/show.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">

    <div class="bordered">

      <div class="pull-right">
        <%= link_to 'Back', admin_teams_path, :class => 'btn' %>
        <%= link_to 'New Player', new_admin_player_path(:team_id => @team.id), :class => 'btn btn-primary' %>
      </div>

      <h2><%= @team.name %></h2>
      <p><strong>Info: </strong> <%= @team.info %></p>

      <h3>Players</h3>

      <table class="table table-striped table-bordered">

        <thead>
          <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>

          <% @team.players.all.each do |player| %>
          <tr>
            <td><%= link_to "#{player.firstname} #{player.surname}", admin_player_path(player) %></td>
            <td><%= player.position %></td>
            <td>
              <%= link_to 'Edit Player', edit_admin_player_path(player), :class => 'btn' %>
              <%= 
                link_to 'Delete Player', '#deleteItem', 
                'data-url' => admin_player_path(player),
                'data-name' => "#{player.firstname} #{player.surname}", 
                :class => 'btn btn-danger delete' 
              %>
            </td>
          </tr>
          <% end %>

          <% if @team.players.all.empty? %>
          <tr>
            <td colspan="3">There are no players.</td>
          </tr>
          <% end %>

        </tbody>

      </table>

    </div>
    
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>