config/routes.rb
Westendathletic::Application.routes.draw do

	root :to => 'home#index'

  namespace :admin do

  	root :to => 'dashboard#index'

	  resource :session,
    	:only => [:new, :create, :destroy]

    resources :users,
      :except => [:show]

    resources :teams, :competitions

    resources :players, :seasons,
      :except => [:index]

    get 'seasons/:id/teams' => 'seasons#teams', :as => :season_teams
    put 'seasons/:id/teams' => 'seasons#update_teams', :as => :season_teams

	end

end

app/models/competition.rb
class Competition < ActiveRecord::Base

  attr_accessible :name

  validates :name, 
  	:presence => true, :length => { :maximum => 255 }

  has_many :seasons

end

app/controllers/admin/competitions_controller.rb
class Admin::CompetitionsController < ApplicationController

	before_filter :authorisation_required

  # GET /admin/competitions
  def index
    @competitions = Competition.all
  end

  # GET /admin/competitions/1
  def show
    @competition = Competition.find(params[:id])
  end

  # GET /admin/competitions/new
  def new
    @competition = Competition.new
  end

  # GET /admin/competitions/1/edit
  def edit
    @competition = Competition.find(params[:id])
  end

  # POST /admin/competitions
  def create
    @competition = Competition.new(params[:competition])

    if @competition.save
      flash[:success] = 'Competition was successfully created.'
      redirect_to admin_competitions_path
    else
      flash.now[:error] = 'Competition creation was unsuccessful.'
      render :new
    end
  end

  # PUT /admin/competitions/1
  def update
    @competition = Competition.find(params[:id])

    if @competition.update_attributes(params[:competition])
      flash[:success] = 'Competition was successfully updated.'
      redirect_to admin_competitions_path
    else
      flash.now[:error] = 'Competition edit was unsuccessful.'
      render :edit
    end
  end

  # DELETE /admin/competitions/1
  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    flash[:notice] = 'Competition was successfully destroyed.'
    redirect_to admin_competitions_path
  end

end

app/views/admin/competitions/_form.html.erb
<%= form_for([:admin, @competition], :html => {:class => 'form-horizontal well'}) do |f| %>

  <fieldset>

    <div class="control-group <%= 'error' if @competition.errors[:name].any? %>">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
        <span class="help-inline"><%= @competition.errors[:name].join(", ") %></span>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', admin_competitions_path, :class => 'btn' %>
    </div>

</fieldset>

<% end %>

app/views/admin/competitions/edit.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">
  	<div class="bordered">
  		<h2>Edit Competition</h2>
    	<%= render 'form' %>
    </div>
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/competitions/index.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">

    <div class="bordered">

      <div class="pull-right">
        <%= link_to 'New Competition', new_admin_competition_path, :class => 'btn btn-primary' %>
      </div>

      <h2>Competitions</h2>     

      <table class="table table-striped table-bordered">

        <thead>
          <tr>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>

          <% @competitions.each do |competition| %>
          <tr>
            <td><%= link_to competition.name, admin_competition_path(competition) %></td>
            <td>
              <%= link_to 'Edit Competition', edit_admin_competition_path(competition), :class => 'btn' %>
              <%= 
                link_to 'Delete Competition', '#deleteItem', 
                'data-url' => admin_competition_path(competition),
                'data-name' => competition.name, 
                :class => 'btn btn-danger delete' 
              %>
            </td>
          </tr>
          <% end %>

          <% if @competitions.empty? %>
          <tr>
            <td colspan="2">There are no competitions.</td>
          </tr>
          <% end %>

        </tbody>

      </table>

    </div>
    
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/competitions/new.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">
  	<div class="bordered">
  		<h2>New Competition</h2>
    	<%= render 'form' %>
    </div>
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>

app/views/admin/competitions/show.html.erb
<%= render 'header' %>

<div class="row">

  <div class="span8">

    <div class="bordered">

      <div class="pull-right">
        <%= link_to 'Back', admin_competitions_path, :class => 'btn' %>
        <%= link_to 'New Season', new_admin_season_path(:competition_id => @competition.id), :class => 'btn btn-primary' %>
      </div>

      <h2><%= @competition.name %></h2>

      <h3>Seasons</h3>

      <table class="table table-striped table-bordered">

        <thead>
          <tr>
            <th>Name</th>
            <th>Start date</th>
            <th>End Date</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>

          <% @competition.seasons.all.each do |season| %>
          <tr>
            <td><%= link_to season.name, admin_season_path(season) %></td>
            <td><%= season.start_date %></td>
            <td><%= season.end_date %></td>
            <td>
              <%= link_to 'Edit Season', edit_admin_season_path(season), :class => 'btn' %>
              <%= 
                link_to 'Delete Season', '#deleteItem', 
                'data-url' => admin_season_path(season),
                'data-name' => season.name, 
                :class => 'btn btn-danger delete' 
              %>
            </td>
          </tr>
          <% end %>

          <% if @competition.seasons.all.empty? %>
          <tr>
            <td colspan="4">There are no seasons.</td>
          </tr>
          <% end %>

        </tbody>

      </table>

    </div>
    
  </div>

  <div class="span4">
    <h2>Sidebar</h2>
  </div>

</div>